<?php
/**
 * Created by PhpStorm.
 * User: jx
 * Date: 2017/3/10
 * Time: 17:22
 */

namespace core\lib;

require_once CORE.'/lib/Smarty/Smarty.class.php';
class Controller extends \Smarty
{
    /*
     * 核心类设置当前控制器调用的模板文件基础目录
     */
    public final function setTemplateDir($template_dir, $isConfig = false)
    {
        if (!file_exists($template_dir)) mkdir($template_dir);
        return parent::setTemplateDir($template_dir, $isConfig); // TODO: Change the autogenerated stub
    }

//    private $templatePath;
//    public final function setTemplatePath($path) {
//        $this->templatePath = $path;
//    }
//    /*
//     * 覆盖父类display方法
//     */
//    public function display($template = null, $cache_id = null, $compile_id = null, $parent = null)
//    {
//        $template = $this->templatePath.$template;
//        parent::display($template, $cache_id, $compile_id, $parent); // TODO: Change the autogenerated stub
//    }
}